:includedir: ../../../
include::{includedir}modules/ROOT/pages/defines/define-all-include.adoc[]
ifdef::env-vscode[]
ifndef::imagesdir[]
:imagesdir: ../../../
endif::imagesdir[]
endif::env-vscode[]

== {name-1on1}の前提条件

{name-1on1}の前提として、2つ条件がある。1つは「対話であること」で、もう1つは「組織や業務のフィードバックループをつくること」である。 [.small]#<<note-前提条件-kome1>>#

[#note-前提条件-kome1, reftext=※1]
[.small]#※1「<<glossary_フィードバックループ>>」の詳細は「<<GLOSSARY>>」を参照#

=== 対話であること
よりよい「対話」をするために、意識することが3つある。

* 「お互いを聴く場にすること」
* 「互いの違いを認識すること」
* 「対話自体のフィードバックループをつくること」



それぞれについて説明していく。 +
1つ目は「お互いを聴く場にすること」である。一方が話すだけ、伝達するだけでは{name-1on1}としては成り立たないということである。例えば、評価面談や会社方針の展開といった打ち合わせ・会議体は、実態としては{name-1on1}ではないケースが多いだろう。 +
2つ目は、「互いの違いを認識すること」である。同じ組織や部署であると、話が通じていると考えがちである。しかし、実際には異なる人間であれば、異なる考え方・捉え方をする。このことを意識をすることで、{name-1on1}がより良いものとなる。 +
3つ目は、「対話自体のフィードバックループをつくること」である。これは、まず受け手が反応を返すこと（フィードバック）、その反応を送り手が受け取ること、そして送り手が再度伝えることの一連の流れを意味している。このループを繰り返すことが大切である。

=== 組織や業務のフィードバックループをつくること

組織内に所属している以上、単に個々の事象では閉じない方がよく、組織の事象が絡むことが多い。 + 
「組織や業務のフィードバックループをつくること」という条件では、3つの観点がある。

* 組織や業務の課題や要望を伝えられている
* 組織や業務の課題や要望に対する結果と理由を返している
* 双方にフィードバックがある