= 一緒に場を作っていくことを確認する
:includedir: ../../../../
include::{includedir}modules/ROOT/partials/defines/define-all-include.adoc[]
ifdef::env-vscode[]
ifndef::imagesdir[]
:imagesdir: ../../../../
endif::imagesdir[]
endif::env-vscode[]

ifdef::site-gen-antora[]
:chapter-number: 7.0
endif::site-gen-antora[]

はじめに::
{name-1on1}の時間を今後どうしていくか、どんな話をしていくのかを改めてお互いが認識をする

要約::
場の定義、目的を確認し、場を一緒に作っていくことを確認しあう

状況::
* {name-1on1}に呼ばれた側が、なぜこの場が設定されたのか分かっていない
* 暗黙的にどちらかが話題提供を求められる
* 相手が話題提供するものだと待ってしまう
* お互いがよくわからないまま進行している

問題::
* 話す場を設けたことが目的となって、何を話していいか困ってしまう
* うまく話し始めることができない
* 話が進まずに沈黙してしまう
* 話してくれているものも、なんの話かわからなくなる
* 世間話や上司からの説教タイムになった結果、嫌な状況が生まれる

フォース::
* 組織から{name-1on1}を実施することだけが求めれて、とりあえずやりだしている
* 設定された側が必要性を感じていないことがある

解決方法::
* 場の定義を伝える、すり合わせする
* そもそもどういう経緯で{name-1on1}が設定されて、組織としての目的をすり合わせする
* 組織としての{name-1on1}目的に加えて、個人の成長などの２人の間で話しをどうフォーカスするのかなど一緒に考える
* どう進めていくかを話す

結果状況::
{name-1on1}という場を一緒につくることで、この場で話す意味を見いだせる

使用例::
まず初回をやってみて:::
とりあえず{name-1on1}をやってみようとなってやってみたらよくわからない時間になってしまった。何を話していいかも、そもそもこの場に意味があるのだろうか。部下のための時間と思っていたけど、待っていても会話が進まなかった。 +
{name-1on1}をやることが先に決まってきて、そもそもどういう場だったのかお互いにわかっていなかったかもしれない。 +
今回は会社からいわれて上司である私から設定したが、近況を話す程度で雑談でおわってしまった。部下側はこっちがリードしてくれるだろうと思っていたかもしれない。 +
このままだとずっとただ雑談をし続けていて、やる意味を失いそうな気がする。会社にいわれたからやるというままでなく、改めて対話する場なのだから一緒にどういうふうに話していくかを考えるところからはじめてみよう。
やっていくうちに:::
{name-1on1}をやる目的や場についてすり合わせしたけれど、話しているうちにネタがなくなってしまった感じがする。当初より早く切り上げることが多くなった。早く終わることは必ずしも悪いことでもないのだけど、一旦原点に立ち止まって場をすり合わせる必要があるのかもしれない。

関連パターン::
* <<_話してもよいことをすり合わせていく>>
* <<_テーマや聴きたいことを備えておく>>



