= 一旦の結論を出して仮置きする
:current2root: ../../../../
:path-partials: {current2root}modules/ROOT/partials/
ifdef::site-gen-antora[]
:path-partials: partial$
endif::site-gen-antora[]
include::{path-partials}defines/define-all-include.adoc[]
ifdef::env-vscode[]
ifndef::imagesdir[]
:imagesdir: ../../../../
endif::imagesdir[]
endif::env-vscode[]


はじめに::
{name-1on1}で出た話題について完全な解決を求めず、まずは一旦の結論を仮置きしてみる。それが間違っていたなら、後から修正すればよいし、動いた結果で後から分かることもある。現状を一歩進めてみよう。

要約::
{name-1on1}で扱うテーマは、そもそも複雑であることが多く、分からないことが多い。そのため、一旦物事を進めてみないと、十分な情報が集まらないこともある。十分な情報がないと、同じようなことを話してしまうかもしれない。まずは一旦の結論を仮置きして進めてみよう。

状況::
* 今話しているテーマ自体が複雑である
* 複雑であるがゆえに、話があちこちに飛んでしまう
* {name-1on1}セッションを複数回やっていても、結局同じような話に終始してしまう／堂々巡りになっている

問題::
* 話はするが、状況が動かない
* 最終結論を出そうとして、先送りになってしまう
* 分からない中で、さらに分からない話が積み上がってしまい、議論が進まない

フォース::
* そもそも複雑なテーマを話していることに気付きにくい
* 解決しないと先に進めないと思ってしまっている

解決方法::
* 最終結論ではない形で、一旦の結論を出す
* その上で、次の動きを進めてみる
* 動いた結果、誤りがあったら訂正する 
*  以下のようなフレーズを利用してみる +
「同じ話になっていそうなので、ここで一旦整理しませんか」 +
「ここまで一旦まとめたので、次の話にしましょうか」

結果状況::
* 堂々巡りにならずに、次のステージの議論ができる
* わかっていることや、本当に議論すべきことが増える

使用例::
{name-1on1}セッションを続けてきて、短期的に成果が出るような目の前の問題には取り組み、成果を出してきているが、そろそろ中長期的な問題に取り組みたいと思っている。しかし、実際話してみると想像以上に根深い。何回かやっていて同じ話になってしまっていそうな気がする。 +
もちろん大事な話なのはわかっているが、ここまでの結論を一旦まとめてしまい、次の話にうつってしまおう。それで動いてみた結果、想定と違ったり、誤りがあったりすれば、また{name-1on1}セッションで議論していこう。



