= お互いの取説を作って更新していく

はじめに::
人はお互い違う特徴、考えを持っているので価値観や特性などお互いのことを知っていきながら仕事を進め方を考える

要約::
仕事の得意不得意、進め方は人によって異なる。それを知るためにはお互いの特性や考え方を知る姿勢をもち、お互いの情報を更新していく

状況::
* 仕事においてこのくらいやるものだろうと思って言った時にやらない場合がある
* 言ったつもりが伝わらない場合がある 
* 相手がやりやすく、自分にはあっていないやり方を提案される
* 結果ではなくやり方の部分が気になってしまう
* 進んでいる状況が見えずにイライラしてしまう

問題::
* お互いの前提を省くと会話が成り立たない場合ややってくれないことへのストレスなどすれ違いが生じる
* 相手のことを想って仕事をアサインしたり、サポートしたつもりが相手が望んでおらず逆効果になる
* 良かれと思って対応したことが裏目に出ることがある

フォース::
* 自分にとっての当たり前は相手にとっては当たり前ではないかもしれない
* 自分にとっての当たり前は気づかないため、お互い意識しないと前提がずれていることに気づけない
* 一度こうだと思い込んでしまうと相手を決めつけてしまう。相手は環境・立場・タイミングで特性が変わることを意識しにくい。

解決方法::
* 仕事の価値観や進め方などをお互い言葉にして相手に伝えてみる
* 違和感を言葉にしてお互いの違いを話してみる
* どういったことが得意不得意かを知っていく
* どのように伝えたらいいか、より伝わる方がわかる状態にする
* 一旦確認して上記のような解決方法を試してみて、反応や実務の様子などをみて、異なると感じたら更新していく。

結果状況::
* お互いに配慮できるため、仕事が円滑に進む
* 仕事を依頼する際にどんなふうに伝えるといいかわかる
* 仕事のレビューや進捗共有を進めていく際にどんな観点が相手が気になっているかを踏まえて共有できる
* 相手と話すなかで自分の特性がわかり、自分からどうしてほしいか言える

使用例::
私の新人時代は仕事を進めるうえでどんどん周りにききながら仕事をしていくタイプなのだが、Aさんはなかなか周りにきかずもくもくと取り組んでおり、声をかけてももう少し時間くださいと言われてしまう。確かに手が止まっているわけではないのだが、こちらとしては状況が気になり、心配になる。 +
 +
そんなことが頻繁に起こっていたので、上司としては心配だし、状況を知りたいという面があること、その上で自分が新人のときは人にきくことで自分の思考が整理されるのでどんどん話かけにいった話をまずしてみた。Aさんは「話すことのほうが仕事勧めやすいのか」と目を丸くして驚いていたようだった。Aさんの話をきいてみると、まずは自分で整理してみないと言葉にだすのが難しいとのこと。まとまってない状態で話しても混乱してしまう。でも進捗が知りたいのは理解したと話してくれた。 +
Aさんが話してくれたおかげで考えていたことが知れてよかった。二人で数日たったら状況だけ共有することとし、Aさんが説明に困っていたら待つことを伝えることができ、お互いのことを知れた。

関連パターン::
* <<_お互いの共通項・違いを知る>>
* <<_相手と自分で共通のメタファーを扱えるようにする>>



