= 1on1ガイド
// 目次
:toc: left
:toclevels: 5
:toc-title: 目次
// このバージョンはPDFでも利用しています。
:revnumber: 0.0.1
:revdate: 2023-03-31
:author: 1on1guide.org
:organization: 1on1guide.org
:homepage: https://github.com/1on1guide-org/
// ソースハイライター設定
:source-highlighter: rouge
:rouge-style: github
:rouge-linenums-mode: inline
include::define-include-all.adoc[]
// ここまで空行禁止(無駄な改行があると設定が有効になりません）

[[PURPOSE-GUIDELINES]]
== 1on1 ガイドの目的
2010年代に入ってから、仕事自体や、仕事に対する価値観が変化していってる。それに伴い、1on1ミーティング（以下、1on1）などで、定期的に話す場を設ける重要性が高まっている。
1on1には様々な形式がある。それに対して、必要となる根本的な部分・考え方の理解を促進するために、本1on1ガイド（以下、本ガイド）を作成した。

私たちは、個の可能性を最大化することで組織の可能性を最大化できる、と考えている。また、各人や各組織で様々なやり方があることも、私たちは理解している。本ガイドは、各人や各組織のやり方を否定するものではない。本ガイドには、あくまで最低限必要な部分や、よりよいやり方を見つけるためのヒントを記載する。
想定読者は、組織に1on1を導入したい人、1on1を実施する人、1on1を受ける人を想定している。

[[PURPOSE-1ON1]]
== 1on1の目的
1on1をなぜ実施するのか。その目的は、組織で働く個人のパフォーマンス向上・維持である。

1on1を実施することで何が起きるのか。1人対1人の対話を通して、以下のことが起きると期待している。
組織で働く個人、あるいは、組織自体の課題を解決する
個人と組織、それぞれの価値観と未来の共有をする


== 1on1の前提条件
1on1の前提として、2つ条件がある。1つは「対話であること」で、もう1つは「組織や業務のフィードバックループをつくること」である。

=== 対話であること
「対話であること」という条件では、意識することが3つある。

. 「お互いに聴く場である」
. 「互いの違いを認識すること」
. 「対話自体のフィードバックループをつくること」

それぞれについて説明していく。
1つ目は「お互いに聴く場である」ということである。一方が話すだけ、伝達するだけでは1on1としては成り立たないということである。例えば、評価面談や会社方針の展開といった打ち合わせ・会議体は、1on1ではないケースが多いだろう。
2つ目は、「互いの違いを認識すること」である。同じ組織や部署であると、つい同じ考えていると考えがちである。しかし、実際には異なる人間であれば、異なる考え方・捉え方をする。それを認識することで、対話として成立する。
3つ目は、「対話自体のフィードバックループをつくること」である。これは、まず受け手が反応を返すこと（フィードバック）、その反応を送り手が受け取ること、そして送り手が再度伝えることの一連の流れを意味している。このループを繰り返すことで、対話が成り立つ。


=== 組織や業務のフィードバックループをつくること

「組織や業務のフィードバックループをつくること」という条件では、3つの観点がある。

* 組織や業務の課題や問題を伝えられている
* 組織や業務の課題や問題に対する結果と理由を返している
* 双方にフィードバックがある


=== 1on1そのものではないこと
翻って、1on1のようでいて、実は1on1そのものを指さないものもある。例えば、単に2人で話す時間をとる、といったことは即ち1on1ということではない。また、隔週から1ヶ月に1回程度実施するなど、定期的な話し合いの場を設けること自体も、1on1ということではない。


== 1on1の価値基準
1on1の実施に際して、以下のようなことを大事にしている。

. 人としての尊重
. 多様性の許容
. プライバシーの尊重
. 「中動態」的な態度
. 不確実性の受容
. 持続可能で小さな成長

=== 人としての尊重

* 意見や振る舞いを尊重する
* お互いの存在を認める

=== 多様性の許容

* 異なる意見や考え方、特性を受け入れる
* 苦手やできないことを受け入れる
* 失敗やネガティブな事柄を受け入れる

=== プライバシーの尊重

* 1on1で会話された内容には多くの個人情報があると考え細心の注意を持って情報を取り扱う
* 1on1内部で話されたことで評価が決まってはいけない
* 組織の改善という目的を忘れて、単に悪い秘密情報をつかむといった浅ましい行動をしてはいけない

=== 「中動態」的な態度

* 互いの意思無しに起こってしまった状況を受け入れる
* 問題の解決を難しくしているもの（フォース）や習慣を受け入れる

=== 不確実性の受容

* わからないことをわからないことと受け入れる
* そもそも組織で働く個人の考え自体、統一的なものはなく不確実である

=== 持続可能で小さな成長

* 組織・現場で変化が起こる
* 個人で振る舞いを選択して変化する
* 無理のない変化である

== 価値基準を満たすための行動
ここまでに挙げた価値基準を満たすため、以下のような行動が基本となる。

状況確認:: 
* 困っていること、コンディション、悩みがあるかなどを確認する
観察:: 
* 1on1の時間以外も含めて、相手がどんな状況にありそうか観察する
並走:: 
* それぞれの役割はあった上で、一緒に進めていく
* 部分では牽引や伴走もあるが、全体では並走する
内省:: 
* 自分の状況を自分で把握する
* 状況と事実と解釈と主観と客観が混ざっていることを踏まえて話してみる・整理する

== 1on1のパターン

=== パターンの記載内容について
パターン名:: 
パターンの内容を簡潔に表す言葉やメタファー

はじめに:: 
サブタイトル的に内容を推測できるもの
どんな状況でどんなことをしてどんな価値を得るのか？を的確に表した言葉

要約:: 
使用例を除く詳細をまとめ理解を促すもの
「パターン名」や「はじめに」ではわからない内容部分を、状況や問題、フォースを簡潔にわかりやすく交えた説明

状況:: 
パターンを適用するべき状況
1on1において対応が必要だと感じる顕在化した状況
1on1上で感じる小さな問題や課題

問題:: 
上記状況を放置することで起こる問題。
もしくは、すでに上記状況に陥ったことで顕在化している問題。
1on1以外で起こる1on1で解決に向かえる問題

フォース:: 
問題に至る背景
問題が起きるほどの状況を生み出してもなお、対応を躊躇う理由。
状況を生み出す暗黙的な価値観や行動

解決方法:: 
パターンの適用を行う際の実際の抽象的な振る舞い

結果状況:: 
パターンの適用が上手くいった状況
解決方法が成功した場合のリターン
要約や問題の裏返しではなく、その先に進んでいる記載だとなお良い。

使用例:: 
カードを切るタイミングや背景
実際の状況などが思い浮かぶ程度に具体的な内容を記載する。
一方で、他の手法そのものや依存した記載をできるだけ避け、読者が自分なりのパターンの適用方法をその都度考えられるように大きな余地を残すことが求められる

関連パターン:: 
関連パターンは大きく分けて以下の二つがある
. 当該パターンを補強したり補完する別のパターン
. 当該パターンの副作用・副反応を避けるために考慮すべきパターン。この場合は逆のパターンなどが挙げられる。


=== カテゴリー

A. その場での振る舞い
B. 感情の取り扱い
C. プロトコルづくり
D. 間合い
E. コンテキスト共有
F. 内外の問題や課題の解決
G. 1on1プロセスの実行と運用

=== パターン

include::patterns/1.adoc[leveloffset=+3]

<<<

include::patterns/2.adoc[leveloffset=+3]

<<<

include::patterns/3.adoc[leveloffset=+3]

<<<

include::patterns/4.adoc[leveloffset=+3]

<<<

include::patterns/5.adoc[leveloffset=+3]

<<<

include::patterns/6.adoc[leveloffset=+3]

<<<

include::patterns/7.adoc[leveloffset=+3]

<<<

include::patterns/8.adoc[leveloffset=+3]

<<<

include::patterns/9.adoc[leveloffset=+3]

<<<

include::patterns/10.adoc[leveloffset=+3]

<<<

include::patterns/11.adoc[leveloffset=+3]

<<<

include::patterns/12.adoc[leveloffset=+3]

<<<

include::patterns/13.adoc[leveloffset=+3]

<<<

include::patterns/14.adoc[leveloffset=+3]

<<<

include::patterns/15.adoc[leveloffset=+3]

<<<

include::patterns/16.adoc[leveloffset=+3]

<<<

include::patterns/17.adoc[leveloffset=+3]

<<<

include::patterns/18.adoc[leveloffset=+3]

<<<

include::patterns/19.adoc[leveloffset=+3]

<<<

include::patterns/20.adoc[leveloffset=+3]

<<<

include::patterns/21.adoc[leveloffset=+3]

<<<

include::patterns/22.adoc[leveloffset=+3]

<<<

include::patterns/23.adoc[leveloffset=+3]

<<<

include::patterns/24.adoc[leveloffset=+3]

<<<




== 用語集

フィードバックループ:: 
反応が返るところまでが本来のフィードバックだが、転じて、その反応を受けて、再度返すところを含めて「フィードバック」としていることもある。ここでは一連の流れ全体を「フィードバックループ」として記載している。

中動態:: 
意思のある「能動態」でも、受け身である「受動態」でもない、昔は存在していたとされる意思の介在しない態。現代では、北海道弁の一部（「押ささる」）に残っているとされる。パターン・ランゲージとの関連としてはフォースとされるものの影響が、心理学との関連としては習慣とされるものが影響している。

プロトコル:: 
慣行や慣習、運用、手順、物事の言い表し方など、組織の文化や個人のバックグラウンド、現場の実情や慣習に応じて成立するコミュニケーションの基本原則。成文化されていない純粋な慣例も多く、その内容は時と必要に応じてさまざまに変化する事を前提としている。

間合い:: 
日常生活の中で、スポーツやコミュニケーション、様々な対人の仕事の現場などに溢れているもの。時間の流れの中で、空間的な位置関係を元に発生するインタラクティブな現象。

コンテキスト:: 
コミュニケーションを成立させる共有情報のこと。言葉の意味には幅があり人や立場、状況やタイミングなどによって意味が異なることが多い。コミュニケーションをとる関係者間でその関係性、背景や状況に対する認識を共有・同意しておくことで会話や理解を成立させることが可能になる。

== 最後に

== ライセンス
include::LICENSE.adoc[leveloffset=+1]

