= 1on1ガイド
// 目次
:toc: left
:toclevels: 5
:toc-title: 目次
// このバージョンはPDFでも利用しています。
:revnumber: 0.0.1
:revdate: 2023-03-31
:author: 1on1guide.org
:organization: 1on1guide.org
:homepage: https://github.com/1on1guide-org/
// ソースハイライター設定
:source-highlighter: rouge
:rouge-style: github
:rouge-linenums-mode: inline
include::define-include-all.adoc[]
// ここまで空行禁止(無駄な改行があると設定が有効になりません）

[[PURPOSE-GUIDELINES]]
== 1on1 ガイドの目的
2010年代に入ってから、仕事自体や、仕事に対する価値観が変化していってる。それに伴い、1on1ミーティング（以下、1on1）などで、定期的に話す場を設ける重要性が高まっている。
1on1には様々な形式がある。それに対して、必要となる根本的な部分・考え方の理解を促進するために、本1on1ガイド（以下、本ガイド）を作成した。

私たちは、個の可能性を最大化することで組織の可能性を最大化できる、と考えている。また、各人や各組織で様々なやり方があることも、私たちは理解している。本ガイドは、各人や各組織のやり方を否定するものではない。本ガイドには、あくまで最低限必要な部分や、よりよいやり方を見つけるためのヒントを記載する。
想定読者は、組織に1on1を導入したい人、1on1を実施する人、1on1を受ける人を想定している。

[[PURPOSE-1ON1]]
== 1on1の目的
1on1をなぜ実施するのか。その目的は、組織で働く個人のパフォーマンス向上・維持である。

1on1を実施することで何が起きるのか。1人対1人の対話を通して、以下のことが起きると期待している。
組織で働く個人、あるいは、組織自体の課題を解決する
個人と組織、それぞれの価値観と未来の共有をする


== 1on1の前提条件
1on1の前提として、2つ条件がある。1つは「対話であること」で、もう1つは「組織や業務のフィードバックループをつくること」である。

=== 対話であること
「対話であること」という条件では、意識することが3つある。

. 「お互いに聴く場である」
. 「互いの違いを認識すること」
. 「対話自体のフィードバックループをつくること」

それぞれについて説明していく。
1つ目は「お互いに聴く場である」ということである。一方が話すだけ、伝達するだけでは1on1としては成り立たないということである。例えば、評価面談や会社方針の展開といった打ち合わせ・会議体は、1on1ではないケースが多いだろう。
2つ目は、「互いの違いを認識すること」である。同じ組織や部署であると、つい同じ考えていると考えがちである。しかし、実際には異なる人間であれば、異なる考え方・捉え方をする。それを認識することで、対話として成立する。
3つ目は、「対話自体のフィードバックループをつくること」である。これは、まず受け手が反応を返すこと（フィードバック）、その反応を送り手が受け取ること、そして送り手が再度伝えることの一連の流れを意味している。このループを繰り返すことで、対話が成り立つ。


=== 組織や業務のフィードバックループをつくること

「組織や業務のフィードバックループをつくること」という条件では、3つの観点がある。

* 組織や業務の課題や問題を伝えられている
* 組織や業務の課題や問題に対する結果と理由を返している
* 双方にフィードバックがある


=== 1on1そのものではないこと
翻って、1on1のようでいて、実は1on1そのものを指さないものもある。例えば、単に2人で話す時間をとる、といったことは即ち1on1ということではない。また、隔週から1ヶ月に1回程度実施するなど、定期的な話し合いの場を設けること自体も、1on1ということではない。


== 1on1の価値基準
1on1の実施に際して、以下のようなことを大事にしている。

. 人としての尊重
. 多様性の許容
. プライバシーの尊重
. 「中動態」的な態度
. 不確実性の受容
. 持続可能で小さな成長

=== 人としての尊重

* 意見や振る舞いを尊重する
* お互いの存在を認める

=== 多様性の許容

* 異なる意見や考え方、特性を受け入れる
* 苦手やできないことを受け入れる
* 失敗やネガティブな事柄を受け入れる

=== プライバシーの尊重

* 個人情報を取り扱うため、注意が必要である
* 1on1内部で話されたことで評価が決まってはいけない
* 組織の改善という目的を忘れて、単に悪い秘密情報をつかむといった浅ましい行動をする

=== 「中動態」的な態度

* 互いの意思無しに起こってしまった状況を受け入れる
* 問題の解決を難しくしているもの（フォース）や習慣を受け入れる

=== 不確実性の受容

* わからないことをわからないことと受け入れる
* そもそも組織で働く個人の考え自体、統一的なものはなく不確実である

=== 持続可能で小さな成長

* 組織・現場で変化が起こる
* 個人で振る舞いを選択して変化する
* 無理のない変化である

== 価値基準を満たすための行動
ここまでに挙げた価値基準を満たすため、以下のような行動が基本となる。

* 状況確認
** 困っていること、コンディション、悩みがあるかなどを確認する
* 観察
** 1on1の時間以外も含めて、相手がどんな状況にありそうか観察する
* 並走
** それぞれの役割はあった上で、一緒に進めていく
** 部分では牽引や伴走もあるが、全体では並走する
* 内省
** 自分の状況を自分で把握する
** 状況と事実と解釈と主観と客観が混ざっていることを踏まえて話してみる・整理する

== 1on1のパターン
=== カテゴリー

A. その場での振る舞い
B. 感情の取り扱い
C. プロトコルづくり
D. 間合い
E. コンテキスト共有
F. 内外の問題や課題の解決
G. 1on1プロセスの実行と運用

=== パターン

1.初期に一緒に場をつくる
2.相手を変えようとしない
3.アドバイスの前に話を「最後まで聴く」
4.思いつきで話してみる
5.自分の感情を言葉にする
6.すべてを言葉通りには受け取らない
7.お互いの共通項・違いを知る
8.1on1の相手と自分の共通のメタファーを知る
9.話してもよいことを例示する
10.対話の間合いを近づける
11.対話の間合いを遠ざける
12.その時のコンディションをお互いに見る
13.背景を知る
14.ステークホルダーや組織の関係や役割を語る
15.一旦の結論を出して仮置きする
16.問題・課題に集中して取り組む
17.あえて解決を目指さない
18.率直に伝える（フランク・フィードバック）
19.初期はリードするためにテーマを持っておく
20.問題と不安を分離する
21.お互いの取説をつくって更新していく
22.あえて利害関係の無い人と1on1をしてみる
23.記憶が薄れない程度の実施になるよう周期を見直す
24.組織の構造を知り、1on1のテーマと照らし合わせる

== 用語集
* フィードバックループ
** 反応が返るところまでが本来のフィードバックだが、転じて、その反応を受けて、再度返すところを含めて「フィードバック」としていることもある。ここでは一連の流れ全体を「フィードバックループ」として記載している。
* 中動態
** 意思のある「能動態」でも、受け身である「受動態」でもない、昔は存在していたとされる意思の介在しない態。現代では、北海道弁の一部（「押ささる」）に残っているとされる。パターン・ランゲージとの関連としてはフォースとされるものの影響が、心理学との関連としては習慣とされるものが影響している。
* プロトコル
** 慣行や慣習、運用、手順、物事の言い表し方など、組織の文化や個人のバックグラウンド、現場の実情や慣習に応じて成立するコミュニケーションの基本原則。成文化されていない純粋な慣例も多く、その内容は時と必要に応じてさまざまに変化する事を前提としている。
* 間合い
** 日常生活の中で、スポーツやコミュニケーション、様々な対人の仕事の現場などに溢れているもの。時間の流れの中で、空間的な位置関係を元に発生するインタラクティブな現象。
* コンテキスト
** コミュニケーションを成立させる共有情報のこと。言葉の意味には幅があり人や立場、状況やタイミングなどによって意味が異なることが多い。コミュニケーションをとる関係者間でその関係性、背景や状況に対する認識を共有・同意しておくことで会話や理解を成立させることが可能になる。

== 最後に

== ライセンス
include::LICENSE.adoc[leveloffset=+1]

