= 1on1 meeting guide writing repository
// ============================================
:url-1on1meeting-guide-file: https://files.1on1guide.org/
:url-1on1meeting-guide-website: https://guide.1on1guide.org/
:link-1on1meeting-guide-file: link:{url-1on1meeting-guide-file}[1on1ガイドのファイル出力]
:link-1on1meeting-guide-website: link:{url-1on1meeting-guide-website}[guide.1on1guide.org]
// ============================================


== 出力先
GitHub actionsのArtifactsとして出力されます。

=== Web上の生成物
* {link-1on1meeting-guide-file} に出力されますが、直接の公開はされません。
** 公開は {link-1on1meeting-guide-website} にて行われます。

== ドキュメント生成方法
mainブランチに対するpullリクエストがあればドキュメント生成を行っておりますが、以下の方法で手動実行することも可能です。

. link:https://github.com/1on1guide-org/1on1meeting-guide/actions/workflows/DryrunGithubPages.yml[Github Actionsの「Dryrun Github Pages」] を開きます
. 「Run workflow」で 「main」ブランチを指定します
. 「Run workflow」ボタンを押下するとドライランを行うことができ、実行したActionのArtifactとしてtarファイルをダウンロード可能です。


== File用サイトのデプロイ方法
リリースを実行すると自動でデプロイされますが、手動でも実行できます。 + 
このデプロイは主にPDFファイルを配置するのに利用しています。

. link:https://github.com/1on1guide-org/1on1meeting-guide/actions/workflows/DeployGithubPages.yml[Github Actionsの「Deploy Github Pages」] を開きます
. 「Run workflow」で 「main」ブランチを指定します。
. 「Run workflow」ボタンを押下し実行してください。

== {link-1on1meeting-guide-website}へのデプロイについて

. link:https://github.com/1on1guide-org/guide.1on1guide.org[Github 1on1guide-org/guide.1on1guide.org リポジトリ」] を参照してください。

== 更新に推奨する環境
Visual Studio CodeとAsciiDoc extensionを利用します。

* link:https://code.visualstudio.com[Visual Studio Code]
* link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc extension]

== ファイル構成

[,tree,subs="attributes+"]
----
.
├─ .github                  (Github向けのファイル)
├─ guide                    (ガイドの構成ファイル)
│ ├─ modules                (Antora buildで必要な構成)
│ │ ├─ contents             (本編の情報)
│ │ │ ├─ pages              (本編のページとなるファイル)
│ │ │ │ └─ patterns         (本編中のパターンファイル Notionから自動で書き出す場合あり)
│ │ │ ├─ partials           (Antoraでページ扱いにならない部品)
│ │ │ │ └─ defines          (本編の設定ファイル)
│ │ │ │   └─ common         (本編以外でも利用する設定ファイル)
│ │ │ ├─ images             (本編で利用する共通的な画像ファイル)
│ │ │ └─ navi.adoc          (Antoraで出力する際のナビゲーションファイル)
│ │ ├─ ROOT                 (ROOTになるコンテンツディレクトリ)
│ │ │ ├─ pages              (indexとなるファイルのみ配置)
│ │ │ ├─ partials           (Antoraでページ扱いにならない部品)
│ │ │ └─ defines            (ROOTの設定ファイル)
│ │ │   └─ common           (本編の設定から共通で持つエイリアス)
│ │ │ └─ images             (ROOTで利用する共通的な画像ファイル)
│ └─antora.yml              (Antoraで出力するためにコンテンツソースルートに配置するメタ情報)
├─ customs                  (出力などの制御に必要な構成ファイル)
│ ├─ common                 (出力などの制御に共通で必要な構成ファイル)
│ ├─ html                   (HTML出力の制御に必要な構成ファイル)
│ ├─ notion2adoc            (Notionで記載したパターンをAsciidocに変換するためのファイル)
│ └─ pdf                    (PDF出力の制御に必要な構成ファイル)
├─ public                   (公開用のディレクトリ)
│ ├─ pdf                    (出力されたPDF)
│ └─ html                   (出力された非公開HTML)
├─ index.adoc               (出力用インデックスファイル)
├─ LICENSE.adoc             (ライセンスを記載したファイル)
└─ README.adoc              (本README)
----

== 管理者
本リポジトリは以下のメンテナーにて管理されています。
コントリビューターについては初回の正式版以降に検討される予定です。

メンテナー::
* link:https://twitter.com/careerupdate[尾澤 愛実]
* 笹尾 納勇仁
* link:https://twitter.com/chachaki[@chachaki]
* link:https://twitter.com/eroccowaruico[@eroccowaruico] 

コントリビューター::
現在はメンテナーが直接レビュー依頼をした方に貢献いただいています。
