:includedir: ../
include::{includedir}contents/defines/define-all-include.adoc[]
ifdef::env-vscode[]
ifndef::imagesdir[]
:imagesdir: ../
endif::imagesdir[]
endif::env-vscode[]

[[PURPOSE-GUIDELINES]]
== {name-this-guide}の目的と背景

2010年代に入ってから、仕事自体や、仕事に対する価値観が変化していってる。それに伴い、1on1ミーティング（以下、1on1）などで、定期的に話す場を設ける重要性が高まっている。 +
1on1には様々な形式がある。それに対して、必要となる根本的な部分・考え方の理解を促進するために、{name-this-guide}（以下、{name-this-guide-raw}）を作成した。

//上記で本書に置き換えたので、この後は全て本書となるように設定 
:name-this-guide: {name-this-guide-raw}

私たちは、個の可能性を最大化することで組織の可能性を最大化できる、と考えている。また、各人や各組織で様々なやり方があることも、私たちは理解している。{name-this-guide}は、各人や各組織のやり方を否定するものではない。  +
そのため、{name-this-guide}は、1on1実践の正解を記した教科書ではなく、あくまで最低限必要な部分や、よりよいやり方を見つけるためのヒントを記載する。{name-this-guide}の内容を参考にしながら、それぞれで実践してもらうことを想定している。 +
想定読者としては、組織に1on1を導入したい人、1on1を実施する人、1on1を受ける人を想定している。 

[NOTE]
.[.navy.big]#*{name-this-guide}はコミュニティで執筆しています*#
====
本書はコミュニティのメンバーが共同で執筆しており特定の人によって完成されたものではなく、常に更新されるものです。また、出版される書籍の文章に比べて足りないと思うところはあるかもしれません。 +
よりよい内容となる記載のアイデアがあれば、こちらに記載ください。
====
