:includedir: ../
include::{includedir}contents/defines/define-all-include.adoc[]
ifeval::[{env} == vscode]
ifndef::imagesdir[]
:imagesdir: ../
endif::imagesdir[]
endif::[]

[[PATTERN-OF-1ON1]]
== {name-this-guide}の構成

=== {name-this-guide}の書き方
{name-this-guide}はパターンランゲージを参考にして書かれている。
パターンランゲージとは、ある分野や領域の実践者に繰り返し見られる振る舞いや行動を 「パターン（パターンランゲージ）」と名付けて、抽出したものである。 +
「<<PATTERN-記載内容>>」に挙げたような記載内容で言語化することで、知見が共有できると考え、この形で整理した。 +
※パターン（パターンランゲージ）についての詳細の説明は割愛するため、参考文献を参照して欲しい。

=== {name-this-guide}の読み方

{name-this-guide}の読み方としては、以下を想定している。

. 「タイトル」と「はじめに」、「要約」を手がかりとして読む
. 「状況」や「課題」を読み、自分に当てはまりそうか、共感できそうかを検討してもらう
. それらの背後にある「フォース」も参考にする 
. ここまでの内容に共感できたら、「解決策」や「結果状況」を読み進めることで、今後のヒントとなると想定している
. 具体的な行動については「使用例」を参考にする
. パターンは互いに関連し、補完し合ったり、相反したりするものがあるため、「関連パターン」を合わせて読むことで、より理解が深まるだろう

また、以下のような様々な用途で読まれることを想定している。

* これから1on1を始める際に、一通り読んで参考にしていただく
* 今実践している1on1で、近しい状況のものを重点的に読んでいただく
* 「<<PATTERN-CATEGORY>>」を見てもらい、興味の湧いたところを抜粋して読んでいただく

[[PATTERN-記載内容]]
=== 記載内容について
タイトル:: 
記載内容を簡潔に表す言葉やメタファー

はじめに:: 
サブタイトル的に内容を推測できるものとして、
どんな状況でどんなことをしてどんな価値を得るのかを記載しています。

要約:: 
使用例を除く詳細をまとめ理解を促すものとして、
「タイトル」や「はじめに」ではわからない内容部分について簡潔にわかりやすく交えた説明をしています。

状況:: 
適用するべき状況を表すものとして、1on1において対応が必要だと感じる顕在化した状況や1on1上で感じる小さな問題や課題を記載しています。

問題:: 
上記状況を放置することで起こる問題もしくは、すでに上記状況に陥ったことで顕在化している問題として、1on1以外で起こる1on1で解決に向かえる問題を記載しています。

フォース:: 
問題に至る背景として、問題が起きるほどの状況を生み出してもなお対応を躊躇う理由や状況を生み出す暗黙的な価値観や行動を記載しています。

解決方法:: 
適用を行う際の実際の抽象的な振る舞いを記載しています。

結果状況:: 
適用が上手くいったのちに現れる状況や解決方法が成功した場合のリターンについて記載しています。

使用例:: 
カードを切るタイミングや背景について、実際の状況などが思い浮かぶ程度に具体的な内容を記載しています。
内容についてはより具体的でありつつ、読者が自分なりの適用方法をその都度考えられるように大きな余地を残すように記載されています。

関連パターン:: 
関連パターンは大きく分けて以下の二つがあります。
* 当該パターンを補強したり補完する別のパターン
* 当該パターンの逆のパターンなどを含む副作用・副反応を避けるために考慮すべきパターン
