:includedir: ../
include::{includedir}contents/defines/define-all-include.adoc[]
ifeval::[{env} == vscode]
ifndef::imagesdir[]
:imagesdir: ../
endif::imagesdir[]
endif::[]

[[GLOSSARY]]
== 用語集

[#glossary_feedbackloop, reftext=フィードバックループ]
フィードバックループ:: 
反応が返るところまでが本来のフィードバックだが、転じて、その反応を受けて、再度返すところを含めて「フィードバック」としていることもある。{name-this-guide}では一連の流れ全体を「フィードバックループ」として記載している。

[#glossary_中動態, reftext=中動態]
中動態:: 
意思のある「能動態」でも、受け身である「受動態」でもない、昔は存在していたとされる意思の介在しない態。現代では、北海道弁の一部（「押ささる」）に残っているとされる。パターン・ランゲージとの関連としてはフォースとされるものの影響が、心理学との関連としては習慣とされるものが影響している。

[#glossary_protocol, reftext=プロトコル]
プロトコル:: 
慣行や慣習、運用、手順、物事の言い表し方など、組織の文化や個人のバックグラウンド、現場の実情や慣習に応じて成立するコミュニケーションの基本原則。成文化されていない純粋な慣例も多く、その内容は時と必要に応じてさまざまに変化する事を前提としている。

[#glossary_間合い, reftext=間合い]
間合い:: 
日常生活の中で、スポーツやコミュニケーション、様々な対人の仕事の現場などに溢れているもの。時間の流れの中で、空間的な位置関係を元に発生するインタラクティブな現象。

[#glossary_context, reftext=コンテキスト]
コンテキスト:: 
コミュニケーションを成立させる共有情報のこと。言葉の意味には幅があり人や立場、状況やタイミングなどによって意味が異なることが多い。コミュニケーションをとる関係者間でその関係性、背景や状況に対する認識を共有・同意しておくことで会話や理解を成立させることが可能になる。

[#glossary_metaphor, reftext=メタファー]
メタファー::
暗喩と呼ばれる比喩表現の一種でありつつ、比喩であることを明示的にしないもの。
物事のある側面をより具体的に想像を喚起する言葉に置き換えることで、簡潔に表現する機能をもつ。
「あれと一緒だよ」といった片方の知識だけで語られるものとは異なり、お互いの経験や知識を使ったたとえ話。

[#glossary_force, reftext=フォース]
フォース::
パワーとは異なる力を表す言葉。{name-this-guide}では特に組織上の特権やランクなどの「権力」、「インセンティブ構造」や「認知バイアス」といった「影響力」を伴う事柄において広範に使っている。
パワーは「スキル」などの能力や、明確な「権限」を指す場合に用いる。