= 背景や経緯を語る

はじめに:: 背景を失った物事は違う意味を持って一人歩きする。事実や決定事項、結果は背景となる情報もセットで伝達してみよう。

要約:: ビジネスでは要点のみをシンプルに伝えることが重要視されるが、それも使い所によって逆効果になるだろう。
1on1を上手に使えば物事の背景を丁寧に伝える有益な時間になって、日常の認識齟齬を徐々に減らすことができるだろう。

状況:: 事業や業務の方向性ややり方だけ示されたり、共有されている場合。
業務の進捗だけ共有され、なぜ今の状況が発生しているか双方の理解が追いついていない場合。
明確な業務要件を満たして完了したのに、根本的なニーズを満たしていない場合。
実際に業務を行うメンバーや決定や結果を受け入れるメンバーの納得感が薄い

問題:: 決定事項に沿ったタスクをこなしたり結果が出されたものの、本来の目的に沿った結果を得られなくなる。
ある目的に沿って業務を行ったのにも関わらず、過去に発生した問題に直面してその業務の進捗を阻害しまう。
ルールが形骸化したまま放置されたり、形骸化したルールの見直し時にインシデントが発生してしまう。
納得感のない業務や結果が増えることで業務全体のモチベーションが低下し、目的を達成するためのコミュニケーションの質が低下する。

フォース:: 背景を共有する意識が薄かったり、背景を共有する必要はないと考えてしまう。
事実や結果や決定事項だけ伝えても背景は想像できるだろうと期待してしまう。
自分はすでに背景を理解しているため、簡単な説明でしっかり相手が理解できると勘違いしてしまう。
相手がすでに背景を知っていると思ってしまう。
受け手がわかった気になりやすいシンプルな言葉だけを伝えたことで、わからないことが分からないまま進めてしまう。

使用例:: 脚本家が俳優にセリフだけ伝えコンテキストを伝えなかったらその物語はリアリティのあるものにはならない。
また、前編のコンテキストを理解しない脚本家が続編を書いたらそれは、前編からの流れを期待する観客の期待する物語にはならないだろう。
業務でも、決定や結果に至るまでのストーリーを多面的に語り、これから作り上げるべきストーリーも合わせて伝えながら、相手の振る舞いがストーリーに沿って目的を達成できるかを確認して進めると良いだろう。

関連パターン:: 

