= アドバイスする前に話を「最後まで聴く」

はじめに::
何かアドバイスや言いたいことが思いついたとしても、まずは最後まで聴くことに徹底する

要約::
経験や知識があると、相談や悩みを聞いた時に自分の視点でコメントが言いたくなることがある。けれども会話を奪ってアドバイスしたり、自分の経験を話そうとするのではなく、まずは相手の話を最後まで聞き、相手の語り終わりまで待とう。解決するのは相談した本人なので、本人の視点で聴き、本人にあった方法を一緒に見つけよう。

状況::
悩んでいることを共有された時や相談された時についついこうしたらいいなぁと浮かんだ時や自分の経験を語りたい、そのままだと失敗してしまうから防いであげたいと思うときがある。 +

* 聞きながらこうした方がいいのではと浮かんだ時
* 自分ならこうするというやり方が浮かんだ時
* 話をきいていて解決できるのにとイライラなどの感情がでたとき

問題::
* 会話を遮って話してしまうことで、話を全然聞いていないと思われてしまう
* アドバイスされた内容がピントがずれていることや相談した側に合っていなかったりする
* アドバイスがあっていたとしても、まだ話している本人が受け入れられる状態、能力、考えではない可能性がある
* アドバイスしてしまうことで相手に頼って考えなくなる、答えをくれるだろうと思ってしまう

フォース::
* 上司（先輩）、部下（後輩）で1on1を行うことが多いので、上司側は似た経験や解決したことがある課題だと思いやすい
* 助けてあげたいと思うとついつい教えたくなる感情が出てくる
* なるべく早く解決したいと思う（何ヶ月も悩まれても困るなど）
* 課題は必ず解決するものだという思い込みがある

使用例::
話をきいているうちに言いたいことが色々と以下のようなことが浮かんでくる。
* 自分だったらこうするのにという解決策
* 自分の経験談
* 要約したくなる
* 結論になかなかたどり着かないので、確認したくなる +
聴いているうちに上記のようなことが浮かび、言いたくなる気持ちはわかる。解決策の１つかもしれない。けれども相手はまだ話しの途中かもしれないし、本当の思いはまだ隠れているかもしれない。途中で話を奪ってしまうと話を聴くよりどうせ自分の話をしたいのだろうと思われてしまうかもしれない。 +
一旦ぐっとこらえて話を最後まで聴いてみよう。最後まで聴いてみると当初思っていなかった場所まで話してくれるかもしれない。まずは、一緒にどうしたらいいか考える土台にたどりつこう。

関連パターン::
<<_相手を変えようとしない>>



