= 話してもよいことをすり合わせていく

はじめに::
1on1の場で話す内容をイメージしやすくすることで安心でき、会話を促進する

要約::
1on1で話す場が与えられても何を話していいかわからないことがある。どこまで何を話していいのか曖昧なため、お互い当たり障りのない会話として雑談などで終えてしまう場合がある。 +
お互いどういった話をしてもいいのかイメージがつくようにすることで、安心して話せる場の形成につながる

状況::
* 1on1の場を設定されても実際どんな話をしていいのかお互いわからないままに進んでしまう場合がある
* 話に詰まってしまったり、何を話していいか困る場面がある
* 1on1でどこまで、なにを話していいのかわからない、どこから話していいのか不明確
* 雑談や最近のことなどお互い当たり障りのない会話をして本質的でない会話で毎回終わってしまう

問題::
* 話すことがなくなってしまうので、話すことがないならと1on1が終了してしまう
* 1on1を行う意義がわからないまま、1on1が繰り返されてしまう
* 本当は話したほうがいい、共有されたほうがいいことが話されずに流れてしまう、認識されずに終わってしまう

フォース::
* 1on1で何を話すものかがそもそもお互い認識がとれていなかったり、知らない
* 進捗共有、評価面談など他会議と1on1との違いがわからない
* 上司相手、会社の人にどこまで話して大丈夫か不安がある
* 話して大丈夫だという安心した関係性が築けていない場合がある

使用例::
1on1が設定されたのの、何を話していいのかわからず当たり障りのない話で終わってしまった。 +
でも相手は最近元気がなくて、なにか抱えているような気がした。最近進捗も気になる部分がある。 +
 +
なにか事情があるなら知りたい。でもまだ話せる関係だと思ってくれていないのかもしれない。こんなこといってもいいのだろうかと悩ませているかもしれない。 +
 +
次回はもう少し踏み込んでどういう話をしていいのか自分からも提案してみよう。そのうえで話しにくくさせているのなら、全部本音でいってくれないかもしれないけど、懸念がどんなことにあるかなども聴いてみよう。きいたからといって責めるわけでもないことを明言してみよう。話すことで少しでもよかったと思ってもらえたらいいな。 +
１回で近づけると思えずに、数回かけて関係性が作れていけるようトライしてみよう。



