= テーマや聴きたいことを備えておく

はじめに::
予めテーマや聴きたいことを持っておくことで、話すことがなくなった場合の手助けになる

要約::
何を話していいか戸惑うケース、雑談で終わってしまうケース、話が続かないケースなど発生することがある。そうなると気まずく感じたり、場の意味を感じられなくなったりすることがある。 +
話すテーマや聴きたいことを準備して相手が話すことがなく困っている場合にはリードすることで会話を進めることができる。

状況::
* 最近どう？といったふんわりした振りになりやすい
* 部下のための時間として構えていると、相手が話ができずに詰まってしまったり、沈黙の時間ができる
* 話題がないな、今日話すことないなという場面に遭遇する

問題::
* 時間を作ったがなんのための時間なのかお互いわからないままに、雑談などを行い、目的なく終了してしまう
* お見合い状態が起きてあたり触りのない会話となってしまったり、なんのための時間がわからないまま終わってしまったりする。
* お互い話す機会がマイナスなイメージで終了してしまう可能性がある

フォース::
* そもそも自分から話すことに慣れていないことも多い
* 突然話そうとしても話を聞く側も悩んでしまう場合がある
* 組織やチームとして1on1をやることが先行して決まっているケースもある
* 自分で何に困っているか、なにを話していいのか認知できていない場合には自分から話し出すのが難しいこともある

解決方法::
* テーマを複数持っておき、インタビューっぽく聞いてみてまず話すことになれてもらう +
＜テーマ例＞
* 仕事の相談など短期的なテーマ
* チームや会社などにおいて思うこと
* キャリアなど長期的なテーマ
* 本人の特性や性格など +
そのほかには +
普段から本人の様子を観察しておくことでテーマを見つけていく方法や、話していくうちにこのテーマ話したいよねとなったらそのテーマについてより深く語ることとする

結果状況::
* どんな話をしていい場なのかイメージができるようになっている
* 戸惑わず進行することようになっている
* 話始められる
* 次回につなげやすくなっている

使用例::
話す場を設定して相手に話すことを促したものの、最近の仕事や雑談をしたところで「何を話したらいいですかね」と会話が止まってしまった。 +
 +
自分のことを語れるタイプや場があれば話すことができる関係性の場合はいいが、確かに「いきなり話せ」と言われても、話すことに慣れていないと戸惑ってしまうようだ。その日は一旦それで終わってしまった。 +
 +
前回の反省を踏まえて、いくつかテーマを用意したり、最近の仕事で気になったことをストックしてみた。一通り相手が話し終わったところでテーマをだしてみると、相手が話やすくなったようで、色々知ることができた。今後も用意しておこう。

関連パターン::
* <<_一緒に場を作っていくことを確認する>>
* <<_話してもよいことをすり合わせていく>>



