= 問題と不安を分離する

はじめに::
不安を感じたら、不安の中から問題を取り出して解決を図ることが重要だ

要約::
不安から行動を起こした結果、同時に不安に着目してしまい不安が増してしまうことがある。 +
1on1を不安と問題を客観的な立場で分離するのに有効な時間として利用してみよう。 +
また対処を試みている問題の解決結果が不明確な時も、実は感じた不安が問題にすり替わっていないか確認してみよう。

状況::
* 課題の解決策に対して元になる課題や問題が明確になっていない
* 解決が困難で結果の見えない問題と戦い続けている
* 不安の解決を求めて時間を使っている
* 問題があると感じるが明確な解決結果が見えない

問題::
不安を抱えたメンバーが組織に不安を解決する力がないと思い込んでしまう +
不安が伝染してチーム全体に不安が渦巻いてしまう +
具体的な不安を口に出すことがなくなり、簡単に解決できる隠れた課題すら隠れてしまう

フォース::
* 不安のようなネガティブな感情をオープンにするのは良くないことだという固定概念
* 不安の詳細を他人と共有するためには勇気が必要
* 不安を感じると、考えるより先に避ける行動をとってしまう
* 不安と問題を一人で分離するのは難しい
* 不安に着目することで不安が増大することがある
* 1つの不安でも要因は複数あるため不安は完全に無くならない事に気づきにくい

使用例::
あるソフトウエアの開発においてスケジュールを大幅に超過することがわかった。 +
チームはスケジュールに対する不安を口にして、毎日打合せを行なっていたが解決することはなかった。 +
メンバーとの1on1の中で不安を分解していくと、スケジュールの遅延の原因は大幅に増加した機能実装だった。 +
対象となる機能は顧客要望による集計機能だった。当初は表形式での表示で提供する予定だったが、便利な機能がないと顧客に使ってもらえないと不安になり、カラムでのソート機能や絞り込み機能を追加していた。さらに集計結果をグラフで表示する機能まで追加されていた。 +
メンバーはその全てがないとお客様が契約を解除してしまうという不安から機能追加を行い、その不安はスケジュールに対する不安、そして顧客と約束した営業メンバーへの不満に繋がっていた。

関連パターン::
<<_あえて解決を急がず、状況を解明する>>



