= あえて利害関係の無い人と実施してみる

はじめに::
実際の利害関係があると話しにくいこともあり、話すことで不可逆な変化が起こってしまう懸念もある。また、同じような人と話すことでいつものパターンに陥ってしまうこともある。その際には、あえて他部署の人や外部の人と{name-1on1}をするなどしてみる方法もある。

要約::
利害関係のある人と対話できるに越したことは無いが、実際には利害関係のある上司や部下との対話には、不可逆な変化が起こってしまうリスクもある。また、同じような人と話すことでいつものパターンに陥ってしまうこともある。その際には、他部署の人や外部の専門家と{name-1on1}を実施してみるという選択肢もあるだろう。

状況::
* 利害関係があることで、本音で話すことにためらいやリスクがある
* 立場や状況的に、間に挟まれてしまっている
* 決まっていない方向性について、曖昧な状態だが話してみたい
* 言っても仕方ない、といった負の期待が出てしまっている

問題::
* 利害関係があると、話すべきことが話せない（知ることができない）
* 利害関係がある人に話したことで、不可逆な変化が起こってしまう
* 話せていても課題や解決策案が「いつものパターン」になりがちである
* 壁打ちができず、検討が進まない、理解が深まらない

フォース::
* 組織構造上、利害関係がある人と{name-1on1}をすることが多い
* 利害関係がないのに{name-1on1}をすることにためらいがある

解決方法::
* 斜め部署やチームと{name-1on1}をする
* 外部の{name-1on1}専門家を呼ぶ
* 悩みや相談ごとに対する専門家と{name-1on1}を実施する

結果状況::
* 本業務に極力影響しない形で壁打ちできて、自身の理解や検討が進む
* いつもとは違う結論や視点を得られる
* 自身の情緒面の整理がつきやすくなる

使用例::
{name-1on1}とは言うものの、その人に言いたいことがあったりするが、利害関係があって話せないことがある。また、その人と長年仕事をしているなどで、{name-1on1}をしても「いつものパターン」になってしまうことがある。 +
そこで、あえて利害関係がない人と{name-1on1}をしてみる。そうすることで本来の業務とは違ったところで壁打ちできて、検討が進むことがあるかもしれない。検討が進むかどうかとは別に、話すことで心理面で自分の中で整理がつくことがあるかもしれない。



