= 言葉に表れない心の動き・意思を大事にする

はじめに::
アドバイスをする、またはアドバイスされる時は、言葉通りに受け止めずに、その言葉の裏側にどのような心の動きがあるのかを大事にすることに合意する

要約::
耳心地が良く綺麗なアドバイスはたくさんあるし、例えば{name-1on1}の相手が上司だと、言われたすべてを言葉通りに受け止めてしまいたくなる。しかし、自分がどうありたいのかや、自分の気持ちや言葉を大事にすることが、他人のアドバイスよりも大事なことも多い。 +
また、アドバイスする側もせっかくの指摘だから、全部言う通りにして欲しい気持ちが少なからずある。しかしながら、アドバイスを受ける側の状況や気持ちを踏まえないとアドバイスが活きるとは限らない。

状況::
* アドバイスや大切にすべきことが多すぎて、聴く側が混乱しかけている
* 特に聴く側が自分に合うかを考えられていない
* 互いの関係性から{name-1on1}の一方の言うことに言い返しにくい +

* 親身になっているからこそ、話す側もとりあえず全部言って受け止めて欲しいと考えてしまう
* 感情は変化するものなのに、「言ったから」とそのまま固定して進めてしまう

問題::
* アドバイスが多くて受け止めきれず、結果うまくいかない
* 自分で考えずに相手に判断を委ねてしまい、結果うまくいかない
* 単に指示を出す側と指示を受ける側という関係性になってしまう
* 言葉で固定してしまうことで、感情が変化しているのにそのまま進めてしまう

フォース::
* 上下関係や力関係、あるいは正論と感じるとそれに流されてしまう
* 効率的にやろうとして、深くつっこまない
* 言葉にできない・なってないものを考えるのが難しい
* 感情が変化することを前提にすること自体に難しさがある

解決方法::
* 心構えとして、言葉がすべてだとは思わないようにする
* 全部を受け止める必要はないことに双方で合意する
* たくさんのアドバイスポイントの中で、どれを大事にしたいかを話し、1〜2つのポイントに絞って取り組む
* 背景にありそうな感情を自分の言葉で表現してみる

結果状況::
* 全部を受け止める必要がないことによる選択・集中ができる
* 相手に合わせることなく、自分の意思を込められる
* 表面上の言葉に惑わされず、その時の言葉として受け止められる

使用例::
例えば、発言量がどちらか一方に偏っていることに気付いた場合、あるいは、相手の反応が薄くなってきた場合など、相手のことを想ってるつもりでも、ヒートアップしてしまい、相手のことを尊重できてないかもしれない。そもそも、アドバイスする側も思いつきで言っていて、順序立ててないこともある。 +
 +
そういった時には、全部を受け止める必要はないことに双方で確認するために、まず、アドバイスのポイントをすべて書き出してみよう。出てきたアドバイスポイントすべてではなく、どれを大事にしたいかを話し、優先順位・順序を決めて、1〜2つのポイントに絞って取り組んでみよう。 +
 +
また、優先順位・順序を決める際には、実行する人の心の動き・意思を踏まえて、一緒に決めていこう。



