= チームの問題はチームの会話で取り扱えるようにする

include::../../../../../guide/modules/contents/partials/defines/define-all-include.adoc[]

はじめに::
チームが抱える問題や課題を1on1に閉じて取り扱い続けることは適切ではない。できる限りチームで会話し解決できるよう流れを作ることを意識して取り組んでみよう。

要約::
チームの問題を1on1だけで解決することはできない。 +
チームの問題を1on1の枠組みだけで解決することは目指さず、チームにフィードバックしてみたり、チームの取り組みに対する個々人へのフィードバックを返す場にしてみるなど、チーム内で積極的に課題解決できる流れを作る必要がある。

状況::
* チームが抱える問題を1on1で解決しようとしている
* チーム内のコミュニケーションを1on1で解決しようとしている
* チーム内の同じ問題が異なるメンバーとの1on1で話題に上がる

問題::
* 当事者であるべきメンバーが課題を意識できないまま問題が解決される
* 当事者不在で解決を急ぐあまり、解決より問題が見えなくなる対処してしまう
* チームメンバー全員で解決を1on1したメンバーだけ負担を負う
* 不透明な意思決定により、チーム内の不信感が高まる

フォース::
* メンバーにネガティブなフィードバックを返したくないと感じている
* コミュニケーションの問題は当事者のみの課題だと思い込んでいる
* チームメンバーが問題を解決できないと思い込んでいる

解決方法::
* チームの問題はチームのミーティングに持ち込む事を提案する
* チームに持ち込むのが難しいと感じる理由を一つずつ整理する
* 実際にチームで会話する内容をシミュレーションしてみる
* 上長やメンターなどチームの外部から支援可能な状況を用意する
* 1on1の中でチームに対する個々人の振る舞いをフィードバックしてみる
* 問題や課題の解決ができなくてもチームメンバーに共有しようと会話してみる

結果状況::
* チームが今より洗練されたプロセスやコミュニケーションプロトコルを確立させている
* 同じような問題が発生しなくなったり、発生してもチーム内で解決可能になっている

使用例::
今のチームに参画した時、明らかにチーム内に問題がありそうなのに、ふりかえりを含めたチームのミーティングでは特に何も触れられていなかった。 +
しばらくメンバーと1on1をする中で、メンバーが1on1の中で個別に解決策を練って個別に動いていることがわかってきた。さらに観察してみるとメンバーはお互いの心証を気を使った発言が多く、チームが抱える問題に対して正直さを欠いたコミュニケーションが見受けられた。 +
そこで、メンバーとの1on1でチームの問題が上がるたび、チームで話せることと話せないことを分類して、チームで話せることはチームのミーティングで会話してもらうようにした。 +
同時に、問題解決につながる議論の方法もミーティングのファリシテーションをサボートとして続けることにした。 +
時間が経つにつれチームのメンバーはすぐに問題を解決できなくても問題を会話できる流れを作れるようになり、1on1でチームの課題を分類する際もチームの中で話せないことが無くなった。




