= 一人で抱えこまない環境をつくる

include::../../../../../guide/modules/contents/partials/defines/define-all-include.adoc[]

はじめに::
問題を抱え込まないようにする環境をつくることで、問題解決や適切な対応の糸口を見つけやすくし、よい結果を得られるようにしよう

要約::
何か問題や悩みがあっても、話せないことや本人にも気付けないことがある。しかし、一人で抱え込み続けてしまうと、その問題自体が周りから見えなくなってしまう。話しにくいこと自体を伝えることを含め、一人で抱え込まない環境をつくることで、問題解決や適切な対応の糸口が見つかりやすくなり、よい結果の兆しがみえる。

状況::
* 抱える問題や悩みについて、話せていない
* 何か悩みがありそうなのに、1on1の場でも話されない

問題::
* 問題を一人で抱え込んでしまうと、その問題自体が他の人から見えなくなったり、その問題の大きさが分からない
* いつの間にか視野が狭まり、他の解決策の可能性や意見を得る機会を逃してしまう
* 結果として、重大なリスクへの対応が遅れる

フォース::
* プライバシーに関わることなので、なかなか開示しにくいケースがある
* 他者に相談すること自体が、仕事ができないことと見なされることを恐れる

解決方法::
* 重要度を自己判断せず、相談してみる。
* 相手のプライバシーを尊重することを表明する。
* 体調が悪そうなど気になる点があれば、声がけをしてみる。
* 話しづらい状況があれば、それを言ってもらう。
* 頼りやすい人をリストアップする。

結果状況::
* 一人で抱え込まず、適切なタイミングで相談することで、問題解決の糸口が見つかりやすくなり、より良い結果が見え始める。
* また、他の視点や意見を得ることで、その後の自身の判断や対応力が向上する。
* 困った時に、他人に頼るというスキルが身につく。

使用例::
あるメンバーが、業務であるクライアントに対して、どのようにアプローチすべきか悩んでいた。チームミーティングは定期的に開かれていたものの、そのクライアントは自分が担当であるし、自分一人の力で解決すべきものだと考えて、特に相談はしていなかった。 +
上司と1on1する機会があり、そういえば気になっていたクライアントについて話してみようと思い、クライアントとの状況を共有して相談を行った。その結果、上司からの新たな視点を得ることができ、適切なアクションを取ることができた。



