= 表現の統一について
ifndef::includedir[]
:includedir: ../../
include::{includedir}contents/defines/define-all-include.adoc[]
endif::includedir[]
ifndef::imagesdir[]
:imagesdir: ../../
endif::imagesdir[]


== 統一した文言など表現ゆれを防ぐための利用

define-\{定義対象}.adocに定義ずみの項目については、本文中に直書きすることなく定義を参照して利用するようお願いします。 +
利用方法は「<<ASCIIDOC-SYNTAX-DEFINE>>」に記載があります。 +
対象の定義ファイルは以下の通りです。

define-literal.adoc:: 表現ゆれを防いだり、記載を容易にするための共通的な表現を定義しています。 +
こちらもindex.adocに記載すると盆雑になるため外部定義となっており、編集中のプレビューもできるように、各ファイルの最上部で条件インクルードされています。
define-imageNicon.adoc:: アイコンやイメージの画像を定義しています。


== 文体の整理

本ドキュメントでは、原則として"...です。...ます。"調の敬体（丁寧体）で記載し、常体（普通体）との混用は避けてください。
ただし、文の途中や、説明のための図の中、箇条書にする部分だけを常体にするなど状況に合わせて整理する必要があります。

その他、記載について迷う場合や統一的な記載を確認する際は以下を参照してください。
link:https://www.microsoft.com/ja-jp/language/styleguides[Microsoft ローカリゼーション スタイル ガイド]


== 画像について

画像はその対象やフォーマット毎のルールや、利用時のルールがあります。

[IMPORTANT]
.[.red.big]#*利用する画像の品質を下げないでください*#
====
画像はドキュメントで見栄えの大きな要素を占めています。 +
このため、画像の品質が低下するとドキュメントの品質が低下したように感じられます。 +
このような印象はエンドユーザーが感じる印象だけでなく、記載に関わる各ステークホルダーにも影響します。 +
結果として「割れ窓理論」的な状況が生まれ、ドキュメント全体の品質を確保できなくなります。 +
もし、今後も記載の有無のラインを一定に保ち、表現ゆれを抑え、仕様網羅可能で、統一感のあるドキュメントを維持したいのであれば、
画像の品質を落とすべきではありません。
====


== セクションの切り方

「<<ASCIIDOC-SYNTAX-SECTION-LEVEL>>」を参考に、他の画面と可能な限り統一感を保って表題をつけてください。

=== セクション内の記載方法

* 原則として手順として必要なものにカウンター機能を付ける
* 項目内の構成について「説明」「画像」の順で記載する +
(画面ページの最上部は概要がない場合「画像」が先行するが概要が上に入るものとする)
* 指摘事項で良く現れる()表記のタイトルやセクション表記は残さず文章になるように変更 +
難しいものは見出しとしてそのままにする


== コントロール名

画面のパーツやコントロールは以下の文言で統一します。

[%header,cols="3,7,3"]
.コントロール名称の一覧
|===
| 利用する名称| 説明 | 利用しない名称
| ドロップダウンリスト | 押すと選択肢がリストで表示されるもの | プルダウンリスト
| ラジオボタン | 主に丸いボタンで複数の選択肢の内一意で選択するもの | オプションボタン
| チェックボックス | 主にチェックいれる四角いボタンで複数の選択肢の内、複数を選択可能なもの |
| コンボボックス | テキスト入力とドロップダウンリストが同一のコントロールで成り立つもの |
| アコーディオン | 表示や入力枠が閉じたり開いたりできるコントロール |
|===


== 文中のカッコの扱いについて

本画面の参照のうち、表外の項目については原則「項目名」を利用します。 +
【〇〇】ボタンのようにコントロール上に表記された項目名は選択肢を除き【項目名】を利用します。 +
（選択肢は現状バラツキあり） +
その他の画面、ロールなど原則として用語定義を利用するものは「」を利用しません。


== OR条件AND条件を日本語で記載する場合

=== OR条件

----
[α]または[β]
[A]、[B]、[C]、もしくは[D]等の[α]、または[E]、[F]、[G]、もしくは[H]などの[β]
----
は
----
α or β
α[A or B or C or D (or etc.)] or β[E or F or G or H (or etc.)]
----
となります。


=== AND条件

----
[α]および[β]
[A]、[B]、[C]、および[D]等の[α]、並びに[E]、[F]、[G]、および[H]などの[β]
----
は
----
α and β
α[A and B and C and D (and etc.)] and β[E and F and G and H (and etc.)]
----
となります。


[[GUIDELINE-DESCRIPTION-DATETIME-FORMAT]]
== 時刻フォーマットの表記

データの項目一覧のフォーマット表記や、スクリーンショット内を置き換える際の日時表記は以下で統一します。

[.accordion]
====
[%header,cols="^2,5,6,^2"]
|===
| 書式指定子 ^| 説明 ^| 使用例 | 表記可否

| d
| 月の日にち (1 ～ 31)
| 2009-06-01T13:45:30 -> 1 +
2009-06-15T13:45:30 -> 15
| ○

| dd
| 月の日にち (01 ～ 31)
| 2009-06-01T13:45:30 -> 01 +
2009-06-15T13:45:30 -> 15
| ○

| ddd
| 曜日の省略名
| 2009-06-15T13:45:30 -> Mon (en-US)
| -

| h
| 12 時間形式の時間 (1 ～ 12)
| 2009-06-15T01:45:30 -> 1 +
2009-06-15T13:45:30 -> 1
| -

| hh
| 12 時間形式の時間 (01 ～ 12)
| 2009-06-15T01:45:30 -> 01 +
2009-06-15T13:45:30 -> 01
| -

| H
| 24 時間形式の時間 (0 ～ 23)
| 2009-06-15T01:45:30 -> 1 +
2009-06-15T13:45:30 -> 13
| ○

| HH
| 24 時間形式の時間 (00 ～ 23)
| 2009-06-15T01:45:30 -> 01 +
2009-06-15T13:45:30 -> 13
| ○

| m
| 分 (0 ～ 59)
| 2009-06-15T01:09:30 -> 9 +
2009-06-15T13:29:30 -> 29
| ○

| mm
| 分 (00 ～ 59)
| 2009-06-15T01:09:30 -> 09 +
2009-06-15T01:45:30 -> 45
| ○

| M
| 月 (1 ～ 12)
| 2009-06-15T13:45:30 -> 6
| ○

| MM
| 月 (01 ～ 12)
| 2009-06-15T13:45:30 -> 06
| ○

| MMM
| 月の省略名
| 2009-06-15T13:45:30 -> Jun (en-US)
| -

| s
| 秒 (0 ～ 59)
| 2009-06-15T13:45:09 -> 9
| -

| ss
| 秒 (00 ～ 59)
| 2009-06-15T13:45:09 -> 09
| ○

| tt
| AM/PM 指定子
| 2009-06-15T13:45:30 -> 午後 (ja-JP)
| -

| yy
| 年 (00 ～ 99)
| 2019-06-15T13:45:30 -> 19
| -

| yyyy
| 年 (4 桁の数値)
| 2009-06-15T13:45:30 -> 2009
| ○

| YYYY
| 暦週の基準年
|
週の開始が月曜日 :  +
1997-12-29T01:09:30 -> 1998 +
週の開始が日曜日 :  +
1998-01-03T13:45:30 -> 1997
| -

| zzz
| UTC を基準とする時間および +
分単位のオフセット
| 2009-06-15T13:45:30-07:00 -> -07:00
| ○
|===
====

詳しくはMicrosoftの 「link:https://docs.microsoft.com/ja-jp/dotnet/standard/base-types/custom-date-and-time-format-strings[カスタム日時形式文字列]」を参照してください。