# This is a AsciiDoctor workflow to help you get started with Actions
name: Dryrun Pages

on:
  workflow_dispatch:
    inputs:
      upload_pages:
        description: 'Upload artifact to GitHub Pages.'
        required: false
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "asciidoctor_job"
  dryrun_job:
    uses: ./.github/workflows/asciidoc.yml
    with:
      upload_pages: ${{ inputs.upload_pages }}
      deploy_pages: false
