# This is a AsciiDoctor workflow to help you get started with Actions
name: Deploy Github Pages

on:
  release:
    types: [released]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "asciidoctor_job"
  release_job:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/asciidoc.yml
    with:
      upload_pages: true
      deploy_pages: true
