# This is a AsciiDoctor workflow to help you get started with Actions
name: Make Artifact And Deploy

# Controls when the action will run. Triggers the workflow on push

on:
  workflow_call:
    inputs:
      deploy_pages:
        description: 'Deploy to GitHub Pages.'
        required: true
        type: boolean
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "asciidoctor_job"
  asciidoctor_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Convert 
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out code
      timeout-minutes: 1
      uses: actions/checkout@v4
    # Copy html assets
    - name: Copy html assets
      timeout-minutes: 1
      run: bash ./customs/html/utils/copy-html-assets.sh
    # Make PDF revision NO.
    - name: Make PDF revision NO.
      timeout-minutes: 1
      run: bash ./customs/pdf/images/title/maketool/revnumber.sh
    # Output command using asciidoctor-action
    - name: Convert AsciiDoc step
      id: documents
      timeout-minutes: 3
      uses: Analog-inc/asciidoctor-action@v1
      with:
        shellcommand: "./.github/workflows/asciidoc.sh"
    # Uploading artifact that can be deployed to GitHub Pages.
    - name: Uploading GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: ./public/
        retention-days: 1


  # Deploy job
  deploy:
    if: inputs.deploy_pages == true  && (github.ref == 'refs/heads/main' || github.event == 'release')
    # Add a dependency to the build job
    needs: asciidoctor_job
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action