# This is a AsciiDoctor workflow to help you get started with Actions
name: Dryrun Github Pages

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "asciidoctor_job"
  dryrun_job:
    uses: ./.github/workflows/asciidoc.yml
    with:
      deploy_pages: false
